name: Main-CI-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, development ]


jobs:
    backend:
        name: Golang CI
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-go@v4
            with:
              go-version: '1.21'
              cache: false
          - name: checkout to directory
            run: cd backend
          - name: golangci-lint
            uses: golangci/golangci-lint-action@v3
            with:
                version: v1.54
          - name: Display Go version
            run: go version
          - name: Install Dependencies
            run: go get ./...
          - name: Build go code
            run: go build
          - name: Test
            run: go test ./... --cover 

    frentend:
        name: Node.js CI
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node-version: [18.x, 20.x]
        steps:
          - uses: actions/checkout@v4
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
          - run: npm ci
          - run: npm run build --if-present
          - run: npm test
          
   
